export const PRODUCT_DB = [
  {
    id: 1,
    title: "Magnetic Building Blocks Set",
    shortDescription: "STEM building kit for kids.",
    fullDescription:
      "This magnetic building blocks set encourages creativity and STEM learning for children aged 5 and above.",
    price: 29.99,
    image: "/images/products/product-img-1.png",
    category: "educational",
    rating: 4.5,
    reviews: [
      "Great for learning!",
      "My kids love it!",
      "High-quality blocks.",
    ],
  },
  {
    id: 2,
    title: "Junior Robotics Kit",
    shortDescription: "Coding and robotics for beginners.",
    fullDescription:
      "A beginner-friendly robotics kit that introduces kids to coding, electronics, and problem-solving.",
    price: 49.99,
    image: "/images/products/product-img-2.png",
    category: "educational",
    rating: 4.7,
    reviews: [
      "Excellent educational toy.",
      "Fun and engaging.",
      "Perfect for STEM projects.",
    ],
  },
  {
    id: 3,
    title: "Science Experiment Kit",
    shortDescription: "Fun science experiments at home.",
    fullDescription:
      "Includes all materials for multiple safe science experiments, helping kids learn basic chemistry and physics.",
    price: 24.99,
    image: "/images/products/product-img-3.png",
    category: "educational",
    rating: 4.6,
    reviews: ["My son loves it!", "Easy instructions.", "Educational and fun."],
  },

  {
    id: 4,
    title: "DIY Craft Kit",
    shortDescription: "Creative arts and crafts for kids.",
    fullDescription:
      "A fun craft kit with everything needed for painting, clay molding, and making personalized art projects.",
    price: 19.99,
    image: "/images/products/product-img-4.png",
    category: "creative",
    rating: 4.3,
    reviews: ["Very creative!", "Kids enjoyed it.", "Good value."],
  },
  {
    id: 5,
    title: "Origami Paper Kit",
    shortDescription: "Learn origami step by step.",
    fullDescription:
      "A colorful origami set that teaches kids to fold and create different shapes while improving fine motor skills.",
    price: 12.99,
    image: "/images/products/product-img-5.png",
    category: "creative",
    rating: 4.4,
    reviews: ["Fun and educational.", "Great for rainy days.", "Easy to use."],
  },
  {
    id: 6,
    title: "Coloring Sticker Book",
    shortDescription: "Interactive coloring and stickers.",
    fullDescription:
      "A fun book combining coloring and stickers, enhancing creativity and hand-eye coordination.",
    price: 9.99,
    image: "/images/products/product-img-6.png",
    category: "creative",
    rating: 4.2,
    reviews: ["Perfect for kids.", "Lots of fun!", "Keeps them busy."],
  },

  {
    id: 7,
    title: "Organic Cotton Baby Onesie",
    shortDescription: "Soft and eco-friendly clothing.",
    fullDescription:
      "Made from 100% organic cotton, this onesie is gentle on baby’s skin and highly durable.",
    price: 17.99,
    image: "/images/products/product-img-7.png",
    category: "clothing",
    rating: 4.8,
    reviews: ["Super soft!", "My baby loves it.", "Good quality."],
  },
  {
    id: 8,
    title: "Kids Character Pajamas",
    shortDescription: "Fun and comfortable sleepwear.",
    fullDescription:
      "Themed pajamas with popular characters, perfect for bedtime comfort and fun.",
    price: 22.99,
    image: "/images/products/product-img-8.png",
    category: "clothing",
    rating: 4.6,
    reviews: ["Cute design.", "Very comfortable.", "Kids adore it."],
  },
  {
    id: 9,
    title: "Personalized Backpack",
    shortDescription: "Customizable bag for school kids.",
    fullDescription:
      "Durable and stylish backpack that can be personalized with your child’s name or favorite design.",
    price: 25.99,
    image: "/images/products/product-img-9.png",
    category: "clothing",
    rating: 4.7,
    reviews: [
      "Excellent quality.",
      "Kids love the personalization.",
      "Spacious and sturdy.",
    ],
  },

  {
    id: 10,
    title: "Soft Plush Teething Toy",
    shortDescription: "Safe and soothing for babies.",
    fullDescription:
      "Soft and safe teething toy made of BPA-free materials, designed to soothe gums and entertain babies.",
    price: 14.99,
    image: "/images/products/product-img-10.png",
    category: "babyEssentials",
    rating: 4.5,
    reviews: ["Very soft.", "Keeps baby engaged.", "Safe to chew."],
  },
  {
    id: 11,
    title: "Baby Bath Toy Set",
    shortDescription: "Fun and safe bath time toys.",
    fullDescription:
      "Includes floating toys, squirt toys, and colorful animals to make bath time fun and educational.",
    price: 18.99,
    image: "/images/products/product-img-11.png",
    category: "babyEssentials",
    rating: 4.4,
    reviews: ["Bath time is fun now!", "Good variety.", "Safe and durable."],
  },
  {
    id: 12,
    title: "Infant Sleep Monitor",
    shortDescription: "Keep track of baby’s sleep.",
    fullDescription:
      "Smart sleep monitor that tracks sleep patterns and provides insights for better rest.",
    price: 59.99,
    image: "/images/products/product-img-12.png",
    category: "babyEssentials",
    rating: 4.6,
    reviews: ["Peace of mind for parents.", "Works great.", "Easy setup."],
  },

  {
    id: 13,
    title: "Mini Balance Bike",
    shortDescription: "First step to learning biking.",
    fullDescription:
      "Lightweight and sturdy balance bike designed for toddlers to learn balance and coordination.",
    price: 79.99,
    image: "/images/products/product-img-13.png",
    category: "outdoor",
    rating: 4.8,
    reviews: ["Excellent beginner bike.", "Sturdy and safe.", "Kids love it!"],
  },
  {
    id: 14,
    title: "Sand and Water Play Set",
    shortDescription: "Fun outdoor activity kit.",
    fullDescription:
      "Encourages creative play outdoors with sand and water games, suitable for backyard or park.",
    price: 34.99,
    image: "/images/products/product-img-14.png",
    category: "outdoor",
    rating: 4.5,
    reviews: ["Hours of fun!", "Durable materials.", "Great for summer."],
  },
  {
    id: 15,
    title: "Kids Mini Soccer Set",
    shortDescription: "Outdoor sports kit for children.",
    fullDescription:
      "Complete beginner soccer kit with mini goal, ball, and cones, perfect for backyard play.",
    price: 39.99,
    image: "/images/products/product-img-15.png",
    category: "outdoor",
    rating: 4.6,
    reviews: ["Perfect size.", "Kids are active now.", "High-quality set."],
  },

  {
    id: 16,
    title: "Interactive Storybook Tablet",
    shortDescription: "Tech learning device for kids.",
    fullDescription:
      "A tablet designed for children with interactive stories, educational games, and safe browsing.",
    price: 89.99,
    image: "/images/products/product-img-16.png",
    category: "tech",
    rating: 4.7,
    reviews: [
      "My child loves it.",
      "Educational and fun.",
      "Very safe device.",
    ],
  },
  {
    id: 17,
    title: "Programmable Robot Pet",
    shortDescription: "Learn coding with fun robotics.",
    fullDescription:
      "Cute robot pet that kids can program to move, dance, and interact, combining play with learning.",
    price: 59.99,
    image: "/images/products/product-img-17.png",
    category: "tech",
    rating: 4.6,
    reviews: ["Super fun!", "Great STEM tool.", "Durable robot."],
  },
  {
    id: 18,
    title: "Kids AR Storybook",
    shortDescription: "Augmented reality reading experience.",
    fullDescription:
      "Storybook that comes alive using AR, making reading interactive and engaging for young children.",
    price: 34.99,
    image: "/images/products/product-img-18.png",
    category: "tech",
    rating: 4.5,
    reviews: [
      "Amazing experience!",
      "Kids are engaged.",
      "Good quality visuals.",
    ],
  },

  {
    id: 19,
    title: "Glow-in-the-Dark Puzzle",
    shortDescription: "Fun puzzle with glowing pieces.",
    fullDescription:
      "Unique puzzle that glows in the dark, combining fun and problem-solving skills for kids.",
    price: 14.99,
    image: "/images/products/product-img-19.png",
    category: "fun",
    rating: 4.4,
    reviews: ["Fun at night!", "Challenging but doable.", "Kids love it."],
  },
  {
    id: 20,
    title: "Character-Themed Birthday Kit",
    shortDescription: "Complete party set for kids.",
    fullDescription:
      "Includes decorations, plates, and party favors for a fun and memorable birthday.",
    price: 29.99,
    image: "/images/products/product-img-20.png",
    category: "fun",
    rating: 4.5,
    reviews: ["Everything I needed.", "Kids loved the theme.", "Good quality."],
  },
  {
    id: 21,
    title: "Subscription Box for Crafts",
    shortDescription: "Monthly creative activity kit.",
    fullDescription:
      "A subscription box delivered monthly with new crafts, puzzles, and activities for kids aged 5–10.",
    price: 24.99,
    image: "/images/products/product-img-21.png",
    category: "fun",
    rating: 4.6,
    reviews: ["Excited every month!", "Fun and educational.", "Great idea."],
  },
]
